version: '3.8'

services:
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    secrets:
      - backend_env
    environment:
      NODE_ENV: production
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: limited_user
      POSTGRES_PASSWORD: secure_password
      POSTGRES_DB: application_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

secrets:
  backend_env:
    file: ./secrets/backend.env

volumes:
  postgres-data:
